config/routes.rb
LocalboardV1::Application.routes.draw do
  get 'pages/home'

  get 'pages/about'

  get 'pages/help'

  get 'pages/media'

  get 'pages/contact'

  resources :post_categories

  resources :posts

  resources :locations

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root :to => "pages#home"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  devise_scope :user do
    get "register", :to => "devise/registrations#new", :as => :register
    get "login", :to => "devise/sessions#new", :as => :login
    get "logout", :to => "devise/sessions#destroy", :as => :logout
  end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
	has_many :posts
end

app/controllers/post_categories_controller.rb
class PostCategoriesController < ApplicationController
  before_action :set_post_category, only: [:show, :edit, :update, :destroy]

  # GET /post_categories
  # GET /post_categories.json
  def index
    @post_categories = PostCategory.all
  end

  # GET /post_categories/1
  # GET /post_categories/1.json
  def show
  end

  # GET /post_categories/new
  def new
    @post_category = PostCategory.new
  end

  # GET /post_categories/1/edit
  def edit
  end

  # POST /post_categories
  # POST /post_categories.json
  def create
    @post_category = PostCategory.new(post_category_params)

    respond_to do |format|
      if @post_category.save
        format.html { redirect_to @post_category, notice: 'Post category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @post_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_categories/1
  # PATCH/PUT /post_categories/1.json
  def update
    respond_to do |format|
      if @post_category.update(post_category_params)
        format.html { redirect_to @post_category, notice: 'Post category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_categories/1
  # DELETE /post_categories/1.json
  def destroy
    @post_category.destroy
    respond_to do |format|
      format.html { redirect_to post_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_category
      @post_category = PostCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_category_params
      params.require(:post_category).permit(:name, :description, :alias)
    end
end

app/helpers/post_categories_helper.rb
module PostCategoriesHelper
end

app/views/post_categories/_form.html.erb
<%= simple_form_for(@post_category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :alias %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/post_categories/edit.html.erb
<h1>Editing post_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_category %> |
<%= link_to 'Back', post_categories_path %>

app/views/post_categories/index.html.erb
<h1>Listing post_categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Alias</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_categories.each do |post_category| %>
      <tr>
        <td><%= post_category.name %></td>
        <td><%= post_category.description %></td>
        <td><%= post_category.alias %></td>
        <td><%= link_to 'Show', post_category %></td>
        <td><%= link_to 'Edit', edit_post_category_path(post_category) %></td>
        <td><%= link_to 'Destroy', post_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post category', new_post_category_path %>

app/views/post_categories/new.html.erb
<h1>New post_category</h1>

<%= render 'form' %>

<%= link_to 'Back', post_categories_path %>

app/views/post_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post_category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post_category.description %>
</p>

<p>
  <strong>Alias:</strong>
  <%= @post_category.alias %>
</p>

<%= link_to 'Edit', edit_post_category_path(@post_category) %> |
<%= link_to 'Back', post_categories_path %>