config/routes.rb
LocalboardV1::Application.routes.draw do
  get 'pages/home'

  get 'pages/about'

  get 'pages/help'

  get 'pages/media'

  get 'pages/contact'

  resources :post_categories

  resources :posts

  resources :locations

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root :to => "pages#home"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  devise_scope :user do
    get "register", :to => "devise/registrations#new", :as => :register
    get "login", :to => "devise/sessions#new", :as => :login
    get "logout", :to => "devise/sessions#destroy", :as => :logout
  end
end

app/views/layouts/_footer.html.erb
<div class="copyright">
	<div class="container">
		<div class="row">
			<div class="col-md-8">						
	            <p class="copyright-space">
                    Copyright © 2014 Local Board | 
                    <%= link_to "About", pages_about_path %>
                </p>
			</div>
      <div class="fb-like col-md-2 color-green" data-href="https://www.facebook.com/thehomesquare" data-layout="standard" data-action="like" data-show-faces="false" data-share="false" data-colorscheme="dark"></div>
			<div class="col-md-2">
				<ul class="social-icons pull-right">
                    <li><a href="https://www.facebook.com/thehomesquare" data-original-title="Facebook" class="social_facebook"></a></li>
                    <li><a href="https://twitter.com/thehomesquare" data-original-title="Twitter" class="social_twitter"></a></li>
                </ul>
			</div>
		</div><!--/row-->
	</div><!--/container-->	
</div>

app/views/layouts/_header_not_signed_in.html.erb
<!--=== Header ===-->    
<div class="header">
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to 'LocalBoard', root_path, class: 'navbar-brand' %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-responsive-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to "Log In", new_user_session_path, :class => "btn-u" %></li>
                </ul>
                         
            </div><!-- /navbar-collapse -->
        </div>    
        <div class="header-divider"></div>  
    </div>    
</div><!--/header-->
<!--=== End Header ===-->             

app/views/layouts/_header_signed_in.html.erb
<!--=== Header ===-->    
<div class="header margin-bottom-20">
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to 'LocalBoard', root_path, class: 'navbar-brand' %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-responsive-collapse">
                <ul class="nav navbar-nav navbar-right">

                   <!-- user login dropdown start-->
                   <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false">
                       <span class="username"><%= current_user.full_name %></span>
                       <i class="fa fa-angle-down"></i>
                   </a>
                   <ul class="dropdown-menu">
                    <%= link_to user_path(current_user), :class => "list-group-item"   do %>
                      <i class="fa fa-user"></i>&nbsp;&nbsp;  Profile
                    <% end %>
                    <%= link_to edit_user_registration_path, :class => "list-group-item"  do %>
                      <i class="fa fa-cogs"></i>&nbsp;&nbsp;  Settings
                    <% end %>
                    <%= link_to logout_path, :class => "list-group-item"  do %>
                      <i class="fa fa-sign-out"></i>&nbsp;&nbsp;  Logout
                    <% end %>
                   </ul>
               </li>
               <!-- user login dropdown end -->

            </ul>
        </div><!-- /navbar-collapse -->


    </div>  
    <div class="header-divider"></div>   
</div>    
</div><!--/header-->

<!--=== End Header ===-->    

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "LocalBoard" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "LocalBoard" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
     <body class="<%= controller_name %> <%= action_name %>">
     <% if user_signed_in? %>

     <%= render 'layouts/header_signed_in' %>
     <div class= "container">

          <%= render 'layouts/messages' %>
          
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>

    <% else %>
    <%= render 'layouts/header_not_signed_in' %>

      <div class="container">
      <%= render 'layouts/messages' %>
      </div>
      
      <%= yield %>
    

    <%= render 'layouts/footer' %>

    <% end %>

    <!-- js placed at the end of the document so the pages load faster -->
    <!--common script for all pages-->
    <%= javascript_include_tag "theme/app" %>

    <script type="text/javascript">
      jQuery(document).ready(function() {
        App.init();
      });
    </script>
  </body>
</html>